'use client';
import {useState,useEffect} from 'react';
import {flushSync} from 'react-dom';
import Panels,{type Locker} from './panels';
import {stops} from './learning';
import {ArrowUpRight,Compass,Layers,Sun,Moon,MoveUpRight,RotateCcw,Footprints} from 'lucide-react';
import World,{zones} from './world';
export default function Home(){const [zone,setZone]=useState(0),[view,setView]=useState('campus'),[day,setDay]=useState(false),[open,setOpen]=useState(false),[traffic,setTraffic]=useState(240),[stop,setStop]=useState(-1),[ready,setReady]=useState(false),[storageError,setStorageError]=useState(false);const [locker,setLocker]=useState<Locker>({saved:[],notes:'',results:[],experiments:[],visited:[0]});
useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('poridhi-locker-v1')||'null');if(value&&Array.isArray(value.saved)&&Array.isArray(value.results)&&Array.isArray(value.experiments)&&Array.isArray(value.visited)&&typeof value.notes==='string')setLocker({saved:value.saved.filter((x:unknown)=>Number.isInteger(x)&&Number(x)>=0&&Number(x)<4),results:value.results.filter((x:unknown)=>typeof x==='string'),experiments:value.experiments.filter((x:unknown)=>typeof x==='string'),visited:[...new Set<number>(value.visited.filter((x:unknown)=>Number.isInteger(x)&&Number(x)>=0&&Number(x)<6))],notes:value.notes});}catch{}setReady(true);},[]);
useEffect(()=>{if(ready)try{localStorage.setItem('poridhi-locker-v1',JSON.stringify(locker));setStorageError(false);}catch{setStorageError(true);}},[locker,ready]);
function go(n:number){setZone(n);setStop(-1);setView('room');setLocker(old=>({...old,visited:Array.from(new Set([...old.visited,n]))}));}
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'navigate_campus',title:'Explore a Poridhi department',description:'Move the camera to a department and open its learning interface.',inputSchema:{type:'object',properties:{department:{type:'integer',minimum:0,maximum:5}},required:['department'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const n=(input as {department?:unknown})?.department;if(typeof n!=='number'||!Number.isInteger(n)||n<0||n>5)throw new Error('Choose a department from 0 to 5.');flushSync(()=>{go(n);setOpen(true);});return {department:zones[n].name,opened:true};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
return <main className="experience"><World zone={zone} view={view} day={day} activity={traffic/100} stop={stop} onZone={go}/><div className="vignette"/><header><a className="brand" href="https://poridhi.io/" target="_blank" rel="noreferrer"><span className="brand-mark">◈</span> PORIDHI<span className="brand-divider"/><small>EXPERIENCE<br/>CENTER</small></a><div className="header-right"><span className="live-dot"/> A SPACE FOR POSSIBILITY <a href="https://poridhi.io/" target="_blank" rel="noreferrer">Classic website <ArrowUpRight size={15}/></a></div></header><section className={`intro ${view!=='campus'?'compact-intro':''}`}><div className="eyebrow">THE CONNECTED CAMPUS / 01</div><h1>Knowledge.<br/>In a new dimension.</h1><p>One connected world to learn, experiment<br/>and build what comes next.</p></section><div className="toolbar"><button onClick={()=>setDay(!day)} aria-label="Toggle architectural daylight">{day?<Moon size={19}/>:<Sun size={19}/>}</button><button onClick={()=>setView('map')} aria-label="View full floor plan"><Layers size={19}/></button><button onClick={()=>setView('walk')} aria-label="Explore at eye level"><Footprints size={19}/></button><button onClick={()=>setView('campus')} aria-label="Reset campus camera"><RotateCcw size={18}/></button></div><div className="location"><span className="eyebrow">YOU ARE EXPLORING</span><h2>{view==='campus'?'The Experience Center':view==='map'?'Campus floor plan':stop>=0?stops[zone][stop]:zones[zone].name}</h2><p><span className="live-dot"/> {view==='walk'?'EYE-LEVEL EXPLORATION':'CONNECTED LEARNING ENVIRONMENT'}</p></div><button className="enter" onClick={()=>{go(zone);setOpen(true);}}><span><small>{view==='campus'?'START YOUR JOURNEY':'OPEN LEARNING INTERFACE'}</small>Explore {zones[zone].short}</span><MoveUpRight size={23}/></button><footer><div className="navigation"><span className="nav-caption"><Compass size={19}/> EXPLORE</span>{zones.map((z,i)=><button key={z.name} onClick={()=>go(i)} className={zone===i&&view!=='campus'?'active':''}><span className="nav-number">0{i}</span>{z.short}</button>)}</div><div className="bottom-meta"><span>DRAG TO ORBIT <i/> SCROLL TO ZOOM <i/> SELECT A DEPARTMENT</span><span>LEARN → EXPERIMENT → ASK → TEST → REMEMBER</span></div></footer>{storageError&&<div role="status" className="storage-warning">Device storage is unavailable. Your locker is kept for this session only.</div>}<Panels open={open} onClose={()=>setOpen(false)} zone={zone} onGo={go} locker={locker} setLocker={setLocker} traffic={traffic} setTraffic={setTraffic} stop={stop} onStop={n=>{setStop(n);setView(zone===0&&n===4?'map':'focus');setOpen(false);}}/></main>}
