'use client';
import {useEffect,useRef} from 'react';
import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export const zones=[{name:'Poridhi Core',short:'Core',tag:'CONNECT',color:'#d5b981',x:0,z:0},{name:'Infrastructure Lab',short:'Lab',tag:'EXPERIMENT',color:'#80d9db',x:-20,z:-13},{name:'Knowledge Library',short:'Library',tag:'LEARN',color:'#dab77d',x:20,z:-13},{name:'Puku AI Hub',short:'Puku AI',tag:'ASK',color:'#b5a1e8',x:-20,z:13},{name:'Challenge Arena',short:'Arena',tag:'TEST',color:'#8bb8e0',x:20,z:13},{name:'Knowledge Locker',short:'Locker',tag:'REMEMBER',color:'#9abea5',x:0,z:27}];
export default function World({zone,view,onZone,day,activity,stop}:{zone:number;view:string;onZone:(n:number)=>void;day:boolean;activity:number;stop:number}){const host=useRef<HTMLDivElement>(null);const state=useRef({zone,view,day,activity,stop});const pick=useRef(onZone);state.current={zone,view,day,activity,stop};pick.current=onZone;
useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false});}catch{el.innerHTML='<p class="webgl-error">This browser cannot start 3D graphics. Use the department navigation to explore the center.</p>';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;el.appendChild(renderer.domElement);
const pmrem=new T.PMREMGenerator(renderer);const environmentScene=new RoomEnvironment();const env=pmrem.fromScene(environmentScene,.06);const scene=new T.Scene();scene.environment=env.texture;scene.environmentIntensity=.4;scene.background=new T.Color('#171e23');scene.fog=new T.FogExp2('#171e23',.008);const camera=new T.PerspectiveCamera(42,1,.1,350);camera.position.set(57,43,66);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2,0);controls.enableDamping=true;controls.dampingFactor=.055;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=4;controls.maxDistance=115;
const hemi=new T.HemisphereLight('#c3dbeb','#33302d',2.1);scene.add(hemi);const sun=new T.DirectionalLight('#ffe4be',3.2);sun.position.set(-30,55,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,far:150});sun.shadow.bias=-.0003;scene.add(sun);
const mats={floor:new T.MeshStandardMaterial({color:'#747876',roughness:.83}),steel:new T.MeshStandardMaterial({color:'#333b40',metalness:.72,roughness:.4}),dark:new T.MeshStandardMaterial({color:'#1c252b',metalness:.45,roughness:.47}),wall:new T.MeshStandardMaterial({color:'#9a9b94',roughness:.88}),wood:new T.MeshStandardMaterial({color:'#8b7050',roughness:.7}),glass:new T.MeshPhysicalMaterial({color:'#91b5bd',metalness:.1,roughness:.15,transparent:true,opacity:.18,side:T.DoubleSide}),green:new T.MeshStandardMaterial({color:'#435c44',roughness:.9})};const lights=(color:string)=>new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:2.3});const warm=lights('#ebce9e');
const surface=document.createElement('canvas');surface.width=256;surface.height=256;const surfaceContext=surface.getContext('2d')!;const pixels=surfaceContext.createImageData(256,256);let seed=318;for(let i=0;i<pixels.data.length;i+=4){seed=(seed*16807)%2147483647;const tone=120+(seed%24);pixels.data[i]=tone;pixels.data[i+1]=tone;pixels.data[i+2]=tone;pixels.data[i+3]=255;}surfaceContext.putImageData(pixels,0,0);const surfaceTexture=new T.CanvasTexture(surface);surfaceTexture.wrapS=surfaceTexture.wrapT=T.RepeatWrapping;surfaceTexture.repeat.set(12,12);mats.floor.bumpMap=surfaceTexture;mats.floor.bumpScale=.025;mats.wall.bumpMap=surfaceTexture;mats.wall.bumpScale=.035;
const geometries:T.BufferGeometry[]=[];const hit:T.Object3D[]=[];function box(w:number,h:number,d:number,x:number,y:number,z:number,mat:T.Material,parent:T.Object3D=scene){const g=new T.BoxGeometry(w,h,d);geometries.push(g);const m=new T.Mesh(g,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function cyl(r:number,h:number,x:number,y:number,z:number,mat:T.Material,parent:T.Object3D=scene){const g=new T.CylinderGeometry(r,r,h,64);geometries.push(g);const m=new T.Mesh(g,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function ring(r:number,t:number,y:number,mat:T.Material,parent:T.Object3D=scene){const g=new T.TorusGeometry(r,t,8,100);geometries.push(g);const m=new T.Mesh(g,mat);m.rotation.x=Math.PI/2;m.position.y=y;parent.add(m);return m;}
function sign(text:string,x:number,y:number,z:number,width:number,color='#eee8d8',parent:T.Object3D=scene){const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle='#182125';ctx.fillRect(0,0,1024,128);ctx.font='500 48px Arial';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,512,80);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(width,width/8),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));m.position.set(x,y,z);parent.add(m);return m;}
box(180,.6,180,0,-.75,0,new T.MeshStandardMaterial({color:'#3c4548',roughness:1}));box(65,.45,67,0,-.25,4,mats.floor);for(let i=-32;i<=32;i+=4){box(.025,.013,66,i,0,4,mats.steel);box(64,.013,.025,0,0,i+4,mats.steel);}box(8,.06,65,0,.02,4,mats.dark);box(61,.06,6,0,.025,0,mats.dark);
const core=new T.Group();scene.add(core);cyl(10.5,.5,0,.25,0,mats.dark,core);cyl(9.8,.12,0,.54,0,mats.floor,core);ring(9.3,.045,.63,warm,core);cyl(3.8,.7,0,1,0,mats.steel,core);cyl(3.5,.12,0,1.4,0,mats.dark,core);ring(3.4,.055,1.49,lights('#a3e0db'),core);
const jewel=new T.Mesh(new T.OctahedronGeometry(2.1,0),new T.MeshPhysicalMaterial({color:'#b5d5d2',metalness:.65,roughness:.12,transparent:true,opacity:.88,clearcoat:1}));jewel.position.y=4.4;core.add(jewel);const edges=new T.LineSegments(new T.EdgesGeometry(jewel.geometry),new T.LineBasicMaterial({color:'#c6f6ec'}));jewel.add(edges);ring(3.1,.06,4.4,mats.steel,core);ring(4,.045,6.4,warm,core);ring(10,.25,8.4,mats.steel,core);ring(9.8,.065,8.2,warm,core);for(let i=0;i<12;i++){const a=i*Math.PI/6;box(.22,8.4,.22,10*Math.cos(a),4.2,10*Math.sin(a),mats.steel,core);if(i%2===0){const g=new T.Group();g.position.set(6.7*Math.cos(a),0,6.7*Math.sin(a));g.rotation.y=-a+Math.PI/2;box(2.8,1,.8,0,1,0,mats.dark,g);const display=box(2.5,.95,.06,0,1.85,-.1,lights('#527c82'),g);display.rotation.x=-.22;core.add(g);}}
const canopy=new T.Mesh(new T.RingGeometry(6.8,10.5,96),mats.steel);canopy.rotation.x=-Math.PI/2;canopy.position.y=8.6;canopy.material=new T.MeshStandardMaterial({color:'#69716f',roughness:.7,metalness:.3,side:T.DoubleSide});core.add(canopy);
sign('P O R I D H I   /   C O R E',0,7.2,6.6,10);const coreHit=cyl(3.8,.05,0,1.55,0,mats.dark);coreHit.userData.zone=0;hit.push(coreHit,jewel);jewel.userData.zone=0;
const pods:T.Mesh[]=[];const roomGroups:T.Group[]=[];zones.slice(1).forEach((z,idx)=>{const n=idx+1;const group=new T.Group();group.position.set(z.x,0,z.z);scene.add(group);roomGroups.push(group);const w=n===5?12:18,d=n===5?10:16;box(w+.6,.4,d+.6,0,.2,0,mats.dark,group);box(w,.12,d,0,.46,0,mats.floor,group);box(w,5.8,.3,0,3.3,-d/2,mats.wall,group);box(.3,5.8,d,-w/2,3.3,0,mats.wall,group);box(.12,5.7,d,w/2,3.3,0,mats.glass,group);box(w,.35,.4,0,6.3,d/2,mats.steel,group);box(w,.35,.4,0,6.3,-d/2,mats.steel,group);for(let x=-w/2;x<=w/2;x+=3){box(.14,5.8,.14,x,3.3,d/2,mats.steel,group);box(.14,.25,d,x,6.4,0,mats.steel,group);}box(w-.5,.08,.1,0,6.05,-d/2+.3,lights(z.color),group);box(w-.6,.04,.08,0,.55,d/2-.15,lights(z.color),group);sign(`0${n}  /  ${z.name.toUpperCase()}`,0,5.1,-d/2+.2,w-1,z.color,group);
const entry=box(3,.06,1.5,0,.56,d/2-.5,mats.dark,group);entry.userData.zone=n;hit.push(entry);const label=sign(z.short.toUpperCase(),0,7.35,d/2,Math.min(w,9),z.color,group);label.userData.zone=n;hit.push(label);
if(n===1){for(let x=-6;x<=6;x+=3){for(let iz=0;iz<2;iz++){const zz=iz*5-3;box(1.8,3.2,1.6,x,2.12,zz,mats.dark,group);for(let u=0;u<9;u++){box(1.57,.23,.05,x,.85+u*.31,zz+.83,mats.steel,group);box(.07,.06,.06,x+.58,.86+u*.31,zz+.88,lights(z.color),group);}for(let p=0;p<3;p++){const pod=box(.35,.35,.35,x+(p-1)*.5,4.2,zz,lights(z.color),group);pods.push(pod);}}}sign('CLUSTER 01     •     TRAFFIC / NODES / SERVICES',0,3.5,-7.75,14,z.color,group);}
if(n===2){for(let x=-6;x<=6;x+=4){box(.18,3.6,9,x,2.3,-1,mats.wood,group);for(let sy=1;sy<4;sy++){box(3.4,.12,1.4,x+1.5,sy,0,mats.wood,group);for(let k=0;k<11;k++)box(.16,.62,.9,x+.1+k*.27,sy+.37,0,new T.MeshStandardMaterial({color:['#9e9c83','#526a70','#ad8769','#414d56'][k%4]}),group);}}box(8,.16,2,0,1.5,5.2,mats.wood,group);for(let x=-3;x<4;x+=3){box(.15,1.4,1.6,x,.8,5.2,mats.steel,group);box(1.1,.08,.75,x,1.63,5.2,warm,group);}}
if(n===3){cyl(3,.5,0,.8,0,mats.dark,group);const orb=new T.Mesh(new T.IcosahedronGeometry(1.5,3),new T.MeshPhysicalMaterial({color:z.color,metalness:.7,roughness:.25,emissive:z.color,emissiveIntensity:.25,wireframe:true}));orb.position.y=3;group.add(orb);pods.push(orb);ring(2.5,.05,1.15,lights(z.color),group);for(let i=0;i<4;i++){const a=i*Math.PI/2;box(2,1,.8,5*Math.cos(a),1,5*Math.sin(a),mats.dark,group);sign('PUKU / RESEARCH',5*Math.cos(a),2,5*Math.sin(a)+.45,2,z.color,group);}}
if(n===4){for(let x=-5;x<=5;x+=5)for(let zz=-3;zz<=3;zz+=6){box(3,.17,1.6,x,1.5,zz,mats.wood,group);box(.2,1.5,1.3,x, .85,zz,mats.steel,group);box(2,.95,.12,x,2.15,zz-.5,lights('#55738a'),group);box(1,.25,1,x,.9,zz+1.5,mats.dark,group);box(1,1,.2,x,1.4,zz+1.9,mats.dark,group);}sign('ENGINEERING ASSESSMENT / 01',0,3.7,-7.75,14,z.color,group);}
if(n===5){for(let x=-4;x<=4;x+=2)for(let y=0;y<2;y++){box(1.8,1.8,.9,x,1.5+y*2,-3,mats.steel,group);box(.5,.15,.06,x+.4,1.5+y*2,-2.5,lights(z.color),group);}box(7,.4,2,0,.8,1.3,mats.wood,group);}
const point=new T.PointLight(z.color,15,15,2);point.position.set(0,4,0);group.add(point);});
// Entrance, reception and landscape share the same structural palette.
box(12,.3,5,0,.2,39,mats.wall);box(.35,5.6,.35,-6,2.9,39,mats.steel);box(.35,5.6,.35,6,2.9,39,mats.steel);box(12.5,.4,6,0,5.8,39,mats.steel);sign('PORIDHI EXPERIENCE CENTER',0,4.8,41.5,11);box(4,1.2,1.2,-3,.9,38,mats.wood);
for(let i=0;i<20;i++){const x=i<10?-34:34,z=(i%10)*7-26;cyl(.7,.6,x,.3,z,mats.dark);cyl(.13,2,x,1.5,z,mats.wood);const tree=new T.Mesh(new T.IcosahedronGeometry(1.6,2),mats.green);tree.scale.y=1.5;tree.position.set(x,3.1,z);tree.castShadow=true;scene.add(tree);box(.08,2,.08,x-2,1,z,mats.steel);box(.5,.08,.5,x-2,2,z,warm);}
const routes:T.Vector3[]=[];for(const z of zones.slice(1)){routes.push(new T.Vector3(0,.13,0),new T.Vector3(z.x,.13,0),new T.Vector3(z.x,.13,z.z));const line=new T.Line(new T.BufferGeometry().setFromPoints(routes.slice(-3)),new T.LineBasicMaterial({color:z.color,transparent:true,opacity:.5}));scene.add(line);}
const packet=new T.Mesh(new T.SphereGeometry(.15,8,8),lights('#b2ece8'));scene.add(packet);let lastZone=-1,lastStop=-2,lastView='',frame=0,transition=0;const endPos=new T.Vector3(),endTarget=new T.Vector3();const clock=new T.Clock();let down=[0,0];function pointerDown(e:PointerEvent){down=[e.clientX,e.clientY];}function pointerUp(e:PointerEvent){if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const found=ray.intersectObjects(hit)[0];if(found)pick.current(found.object.userData.zone);}
renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);controls.addEventListener('start',()=>transition=0);const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(el);resize();
function animate(){frame=requestAnimationFrame(animate);const t=clock.getElapsedTime();const s=state.current;if(s.zone!==lastZone||s.view!==lastView||s.stop!==lastStop){const z=zones[s.zone];if(s.view==='map'){endPos.set(.1,87,10);endTarget.set(0,0,5);}else if(s.view==='campus'){endPos.set(57,43,66);endTarget.set(0,2,4);}else if(s.view==='focus'){if(s.zone===0){const poses=[[19,8,54,0,3,38],[2,2.3,44,0,2,38],[4,3,18,0,3,0],[6,4,9,0,3,0]];const p=poses[Math.min(s.stop,3)];endPos.set(p[0],p[1],p[2]);endTarget.set(p[3],p[4],p[5]);}else{const poses=[[0,2.4,13,0,3,0],[11,10,14,0,2,0],[-3,3.2,6,-3,2,0],[4,3.2,5,3,2,-2],[-5,2.7,2,-4,2,-3],[5,3,5,0,2,-3],[0,2.8,-1,0,3,-7],[6,2.5,3,3,2,-3]];const p=poses[Math.min(s.stop,7)];endPos.set(z.x+p[0],p[1],z.z+p[2]);endTarget.set(z.x+p[3],p[4],z.z+p[5]);}}else if(s.view==='walk'){endPos.set(z.x+1.8,2.3,z.z+7);endTarget.set(z.x,2.5,z.z-3);}else{endPos.set(z.x+13,12,z.z+18);endTarget.set(z.x,2,z.z);}transition=1;lastZone=s.zone;lastView=s.view;lastStop=s.stop;}if(transition){camera.position.lerp(endPos,.045);controls.target.lerp(endTarget,.045);if(camera.position.distanceTo(endPos)<.05)transition=0;}jewel.rotation.y=t*.14;jewel.position.y=4.4+Math.sin(t*.6)*.12;pods.forEach((p,i)=>{p.rotation.y=t*.2;p.position.y+=(Math.sin(t*1.5+i)*.002);});const target=zones[1];const phase=(t*(.12+s.activity*.008))%1;packet.position.set(target.x*phase,.2,target.z*phase);hemi.intensity=s.day?3.4:1.4;sun.intensity=s.day?4:1.6;scene.background=new T.Color(s.day?'#87959d':'#171e23');(scene.fog as T.FogExp2).color.copy(scene.background);controls.update();renderer.render(scene,camera);}animate();return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const arr=Array.isArray(o.material)?o.material:[o.material];arr.forEach(m=>{if(m.map)m.map.dispose();m.dispose();});}});env.dispose();pmrem.dispose();environmentScene.dispose();surfaceTexture.dispose();renderer.dispose();renderer.domElement.remove();};},[]);return <div ref={host} className="world" aria-label="Interactive 3D model of the Poridhi Experience Center"/>;}
