import {modules,type Kind} from './curriculum';
export type Event={name:string;at:number;module:string;action?:string;outcome?:string};
export type State={moduleId:string;step:number;flags:string[];count:number;nodes:number;failedNodes:number;context:number;archived:boolean;recovered:boolean;status:'ready'|'active'|'warning'|'failed'|'success';message:string;reaction:'idle'|'curious'|'thinking'|'working'|'confused'|'success';attempts:number;hints:number;completed:string[];events:Event[];serial:number;lastAction:string;session:number};
export type Action={id:string;label:string;station:number};
export function initialState(id=modules[0].id,completed:string[]=[]):State{return {moduleId:id,step:0,flags:[],count:0,nodes:3,failedNodes:0,context:0,archived:false,recovered:false,status:'ready',message:modules.find(m=>m.id===id)?.story||'',reaction:'curious',attempts:0,hints:0,completed,events:[],serial:0,lastAction:'',session:1};}
const A=(id:string,label:string,station:number):Action=>({id,label,station});
export const actions:Record<Kind,Action[]>={
workflow:[A('inspect','Inspect project',0),A('chat','Ask for a description',0),A('plan','Plan the repair',1),A('edit','Edit project files',2),A('verify','Verify the repair',3)],
permissions:[A('read','Read access policy',0),A('write','Attempt file write',1),A('approve','Request scoped approval',2)],
rules:[A('read','Read CLAUDE.md',0),A('js','Build JavaScript file',1),A('ts','Build TypeScript file',2)],
context:[A('add','Add a document · 25 units',0),A('compress','Summarize context',1),A('prune','Remove a document',2),A('verify','Verify working context',3)],
memory:[A('create','Create a finding',0),A('archive','Store in archive',1),A('end','End this session',2),A('retrieve','Retrieve memory',1),A('verify','Verify recall',3)],
tools:[A('inspect','Inspect the task',0),A('browser','Connect browser tool',1),A('filesystem','Connect filesystem tool',2),A('read','Read build.log',2),A('verify','Verify diagnosis',3)],
project:[A('inspect','Inspect failure logs',0),A('repair','Repair configuration',1),A('test','Run project tests',2),A('activate','Activate workshop',3)],
loop:[A('observe','Observe the project',0),A('plan','Create a plan',1),A('tool','Invoke the edit tool',2),A('result','Inspect tool result',2),A('verify','Verify the change',3)],
mcp:[A('connect','Connect filesystem server',0),A('discover','Discover read_file tool',1),A('authorize','Authorize read scope',2),A('invoke','Invoke read_file',3)],
delegation:[A('research','Assign research',0),A('coding','Assign implementation',1),A('testing','Assign verification',2),A('run','Run the specialists',2),A('synthesize','Synthesize evidence',3)],
guardrails:[A('read','Allow documentation read',0),A('delete','Deny irreversible delete',1),A('deploy','Request deployment approval',2),A('bypass','Try bypassing policy',3)],
design:[A('add','Provision a node',0),A('remove','Remove a healthy node',0),A('fail','Fail one node',1),A('restore','Restore failed node',2),A('verify','Verify resilient capacity',3)],
orchestration:[A('research','Route to research',0),A('implement','Route to coding',1),A('test','Route to testing',2),A('release','Release verified result',3)],
retrieval:[A('port','Retrieve deployment port',0),A('notes','Retrieve meeting notes',1),A('prune','Prune irrelevant notes',2),A('verify','Verify relevance',3)],
capstone:[A('tools','Connect tool layer',0),A('memory','Establish memory',1),A('guardrails','Install guardrails',2),A('test','Test integrated platform',3),A('deploy','Deploy the platform',3)],
container:[A('source','Load application source',0),A('deps','Load dependencies',1),A('build','Build the image',2),A('publish','Publish to registry',3),A('run','Run a container',3)],
cluster:[A('fail','Inject node failure',0),A('add','Provision a node',1),A('restore','Restore failed node',2),A('verify','Verify service recovery',3)],
pipeline:[A('run','Run deployment pipeline',0),A('inspect','Inspect failed checks',1),A('tests','Repair failing tests',2),A('security','Update vulnerable dependency',3)],
production:[A('inspect','Inspect logs & timeline',0),A('diagnose','Identify release regression',1),A('scale','Add compute capacity',2),A('rollback','Roll back to v1',2),A('verify','Verify recovery',3)]};
export function transition(previous:State,action:string,now=Date.now()):State{
const module=modules.find(m=>m.id===previous.moduleId)!;if(!module)throw new Error('Unknown module');if(!actions[module.kind].some(a=>a.id===action))throw new Error('Unknown action');
const s:State={...previous,flags:[...previous.flags],events:[...previous.events],completed:[...previous.completed],serial:previous.serial+1,lastAction:action,reaction:'working',status:'active'};
const has=(f:string)=>s.flags.includes(f);const flag=(f:string)=>{if(!has(f))s.flags.push(f);};
const say=(m:string)=>{s.message=m;};const fail=(m:string)=>{s.status='failed';s.reaction='confused';s.attempts++;say(m);};
const pass=(m:string)=>{s.status='success';s.reaction='success';say(m);if(!s.completed.includes(s.moduleId)){s.completed.push(s.moduleId);s.events.push({name:'competency_demonstrated',module:s.moduleId,at:now});}};
const seq=(items:string[],messages:string[])=>{const next=items[s.step];if(action!==next){fail(`That operation needs the previous stage. Next: ${actions[module.kind].find(a=>a.id===next)?.label||'replay the mission'}.`);return;}s.step++;say(messages[s.step-1]);if(s.step===items.length)pass(messages[s.step-1]);};
switch(module.kind){
case 'workflow':if(action==='chat'){say('Puku can describe a repair, but the files and tests have not changed. The workshop is still offline.');s.reaction='thinking';}else seq(['inspect','plan','edit','verify'],['Observed: sign-in config is missing. The filesystem now exposes the broken file.','Plan recorded: restore the missing configuration, then run the test.','Project file updated. The result is not verified yet.','Verified: sign-in test passes. Puku has closed the agentic loop.']);break;
case 'permissions':if(action==='read'){flag('policy');say('Training policy: reads are allowed. File writes require scoped approval.');}if(action==='approve'){if(!has('policy'))fail('Inspect the scope before asking for permission.');else{flag('approved');say('A simulated reviewer approved this project-file write. The gate opens for this operation only.');}}if(action==='write'){if(!has('approved')){flag('blocked');fail('Write blocked. Puku has a tool, but does not have permission to use it for this operation.');}else if(!has('blocked'))say('Write authorized. To complete the comparison, replay and experience the restricted operation first.');else pass('Authorized write complete. You experienced the boundary and requested the right scope.');}break;
case 'rules':if(action==='read'){flag('read');say('CLAUDE.md: use TypeScript for new application files. Validate the convention before accepting a change.');}else if(!has('read'))fail('Puku has not read the project instructions yet.');else if(action==='js'){flag('conflict');fail('Convention conflict: app.js does not match the TypeScript rule. This training validator rejected the file.');}else if(!has('conflict')){say('TypeScript matches the convention. First try the conflicting builder to see the rule’s effect.');}else pass('app.ts accepted. Puku used the project constitution and verified the output.');break;
case 'context':if(action==='add'){s.context+=25;if(s.context>100){flag('overflow');fail(`Context is ${s.context}/100. The chamber overflowed. Compress or prune before continuing.`);}else say(`${s.context}/100 training units occupied. Added a document to working context.`);}if(action==='compress'){if(!s.context)fail('There is no working context to summarize.');else{s.context=Math.ceil(s.context*.4);flag('summary');say(`Summary created: ${s.context}/100 units remain. Details may be lost; verify the task still has the essential information.`);}}if(action==='prune'){s.context=Math.max(0,s.context-25);say(`Removed a document. ${s.context}/100 units remain.`);}if(action==='verify'){if(has('overflow')&&has('summary')&&s.context>0&&s.context<=100)pass('Working context is within budget. You recovered from overflow using summarization.');else fail('Demonstrate overflow, summarize the contents, and verify a non-empty chamber within its 100-unit budget.');}break;
case 'memory':if(action==='create'){flag('finding');s.context=25;s.recovered=false;say('Working context now contains: the service listens on port 8080.');}if(action==='archive'){if(!has('finding'))fail('There is no finding to store.');else{s.archived=true;say('The port finding is now in persistent memory. Ending the session will not delete it.');}}if(action==='end'){s.context=0;s.flags=s.flags.filter(f=>f!=='finding');s.session++;flag('session-ended');s.recovered=false;say(s.archived?'Short-term context cleared. The archive still holds the finding.':'Short-term context cleared. The finding is lost because it was not archived.');}if(action==='retrieve'){if(!s.archived)fail('The archive is empty. Create and store a finding first.');else{s.context=25;s.recovered=true;flag('finding');say('Retrieved port 8080 from the archive into this session.');}}if(action==='verify'){if(s.archived&&s.recovered&&has('session-ended'))pass('Recall verified across the session boundary. Persistent memory becomes useful when retrieved.');else fail('Store the finding, end the session, retrieve it, then verify recall.');}break;
case 'tools':if(action==='inspect'){flag('task');say('Task: diagnose the local build failure. Evidence: /project/build.log.');}if(action==='browser'){s.flags=s.flags.filter(f=>f!=='filesystem');fail('The browser tool cannot read this local build log. Choose a capability that matches the input.');}if(action==='filesystem'){flag('filesystem');say('Filesystem tool connected with read access to /project.');}if(action==='read'){if(!has('filesystem')||!has('task'))fail('Inspect the task and connect the filesystem tool first.');else{flag('evidence');say('build.log: missing environment variable SERVICE_PORT. This is the evidence for the diagnosis.');}}if(action==='verify'){if(has('evidence'))pass('Diagnosis verified from tool output: SERVICE_PORT is missing.');else fail('Read the log before claiming a diagnosis.');}break;
case 'project':seq(['inspect','repair','test','activate'],['The startup log reports missing SERVICE_PORT.','Configuration repaired: SERVICE_PORT=8080.','All training checks pass. The activation switch is now ready.','Workshop activated. A verified repair brought the facility online.']);break;
case 'loop':seq(['observe','plan','tool','result','verify'],['Observation captured: one failing test.','A targeted change is planned.','Tool executed and returned an output. Inspect that output next.','Result observed: file changed; one test now passes.','The feedback loop is complete and the change is verified.']);break;
case 'mcp':seq(['connect','discover','authorize','invoke'],['Filesystem server connected to the MCP port.','Discovered read_file(path) with a project-scoped read capability.','Read scope authorized for the training project.','read_file returned project information through the standard connection.']);break;
case 'delegation':if(['research','coding','testing'].includes(action)){flag(action);say(`${action} responsibility assigned to a specialist.`);}if(action==='run'){if(['research','coding','testing'].every(has)){flag('results');say('All three specialists returned evidence: diagnosis, patch and test result.');}else fail('Assign research, coding and testing before running the team.');}if(action==='synthesize'){if(has('results'))pass('Evidence synthesized into one verified repair. Puku remains responsible for the combined result.');else fail('There are no specialist results to synthesize yet.');}break;
case 'guardrails':if(action==='bypass')fail('The policy cannot be bypassed. Choose an explicit decision for each operation.');else{flag(action);say(action==='read'?'Documentation read allowed.':action==='delete'?'Irreversible delete denied. The project remains intact.':'Deployment routed to a simulated human approval checkpoint.');if(['read','delete','deploy'].every(has))pass('All operations routed correctly: allow, deny and ask for approval.');}break;
case 'design':case 'cluster':if(action==='add'){s.nodes=Math.min(8,s.nodes+1);say(`Provisioned ${s.nodes} nodes. Healthy capacity: ${(s.nodes-s.failedNodes)*100} req/s.`);}if(action==='remove'){s.nodes=Math.max(s.failedNodes+1,s.nodes-1);say(`Node removed. Healthy capacity: ${(s.nodes-s.failedNodes)*100} req/s.`);}if(action==='fail'){s.failedNodes=Math.min(s.nodes,s.failedNodes+1);flag('failure-seen');fail(`Node failed. ${(s.nodes-s.failedNodes)*100} req/s healthy capacity remains for 240 req/s traffic.`);}if(action==='restore'){s.failedNodes=Math.max(0,s.failedNodes-1);say(`Node restored. ${(s.nodes-s.failedNodes)*100} req/s capacity is healthy.`);}if(action==='verify'){const enough=(s.nodes-s.failedNodes)*100>=240;if(enough&&has('failure-seen')&&(module.kind==='cluster'||s.failedNodes>0))pass('Service verified: surviving healthy capacity serves the complete 240 req/s workload.');else fail(module.kind==='design'?'Verify sufficient capacity while at least one node remains failed.':'Inject a failure, recover sufficient capacity, then verify the service.');}break;
case 'orchestration':seq(['research','implement','test','release'],['Research unit returned a diagnosis. The coding dependency is ready.','Coding unit returned a patch. Testing now has an artifact.','Testing unit verified the patch.','Verified result released. The handoffs respected their dependencies.']);break;
case 'retrieval':if(action==='port'){flag('port');s.context=has('notes')?75:25;say('Relevant memory retrieved: deployment port is 8080.');}if(action==='notes'){flag('notes');s.context=has('port')?75:50;say('Meeting notes retrieved. They consume context but do not answer the port question.');}if(action==='prune'){s.flags=s.flags.filter(f=>f!=='notes');s.context=has('port')?25:0;say('Unrelated notes removed from the working context.');}if(action==='verify'){if(has('port')&&!has('notes'))pass('Relevant retrieval verified: the context contains the port record without unrelated notes.');else fail('The working context must contain the port record and exclude unrelated notes.');}break;
case 'capstone':if(['tools','memory','guardrails'].includes(action)){flag(action);say(`${action} subsystem connected to the platform.`);}if(action==='test'){if(['tools','memory','guardrails'].every(has)){flag('tested');say('Integration checks pass: authorized tools, persistent state and boundaries are connected.');}else fail('The platform is incomplete. Connect tools, memory and guardrails.');}if(action==='deploy'){if(has('tested'))pass('Agent platform deployed in the training world. Its essential boundaries and capabilities are verified.');else fail('Test the integrated platform before deploying.');}break;
case 'container':if(action==='source'||action==='deps'){flag(action);say(action==='source'?'Application source loaded into the factory.':'Pinned dependencies loaded into the factory.');}if(action==='build'){if(has('source')&&has('deps')){flag('image');say('Image built from application source and dependencies.');}else fail('The image needs both application source and dependencies.');}if(action==='publish'){if(has('image')){flag('registry');say('Built image published to the training registry.');}else fail('Build the image before publishing it.');}if(action==='run'){if(has('registry'))pass('Container started from the registry image. A packaged template became a running service.');else fail('Publish an image before starting a container from this registry.');}break;
case 'pipeline':if(action==='inspect'){flag('inspected');say('Failed checks: sign-in test fails; dependency scanner reports a vulnerable version.');}if(action==='tests'||action==='security'){if(!has('inspected'))fail('Inspect the failed checks before changing the release.');else{flag(action);say(action==='tests'?'Failing test repaired.':'Vulnerable dependency updated.');}}if(action==='run'){if(has('tests')&&has('security'))pass('Build → tests → security → package → deploy → monitor: all gates pass. The service is live in the training world.');else{flag('failure-seen');s.step=has('tests')?3:2;fail(has('tests')?'Pipeline stopped at security. The vulnerable dependency still needs repair.':'Pipeline stopped at tests. The release has not reached deployment.');}}break;
case 'production':if(action==='scale'){s.nodes++;say('More compute added, but the application regression remains. Error rate is still 24%.');}else seq(['inspect','diagnose','rollback','verify'],['Logs: errors began at the v2 rollout; v1 baseline was healthy.','Diagnosis: v2 introduced a configuration regression, not a capacity shortage.','Rolled back to v1. Error rate fell from 24% to 0.2%; latency returned from 900ms to 90ms.','Recovery verified from error rate and latency. The incident is resolved.']);break;
}
s.events.push({name:'action_performed',module:s.moduleId,at:now,action,outcome:s.status});s.events=s.events.slice(-500);return s;
}
export function machineFill(s:State){const k=modules.find(m=>m.id===s.moduleId)!.kind;if(k==='context'||k==='memory'||k==='retrieval')return s.context;return s.status==='success'?100:Math.min(90,Math.max(s.step*20,s.flags.length*20));}
export function getMetrics(s:State){const k=modules.find(m=>m.id===s.moduleId)!.kind;if(['context','memory','retrieval'].includes(k))return [{label:'Working context',value:`${s.context}/100`},{label:'Memory archive',value:s.archived?'1 finding':'Empty'}];if(k==='cluster'||k==='design')return [{label:'Healthy nodes',value:`${s.nodes-s.failedNodes}/${s.nodes}`},{label:'Capacity / demand',value:`${(s.nodes-s.failedNodes)*100} / 240 req/s`}];if(k==='production')return [{label:'Error rate',value:s.step>=3?'0.2%':'24%'},{label:'Latency',value:s.step>=3?'90 ms':'900 ms'}];return [{label:'System state',value:s.status==='success'?'Verified':s.status==='failed'?'Needs attention':s.step||s.flags.length?'In progress':'Ready'},{label:'Evidence',value:`${s.step+s.flags.length} steps`}];}
