'use client';
import {useEffect,useRef} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {BRAND,milestones,modules} from './curriculum';
import {createPuku} from './character';
import {machineFill,type State,type Action} from './engine';
export type Command={action:Action;nonce:number};
export type SceneProps={state:State;selected:number;command:Command|null;view:'follow'|'map'|'close';paused:boolean;reduced:boolean;speed:number;quality:'low'|'medium'|'high';onStation:(n:number)=>void;onArrive:(id:string)=>void;onNear:(near:boolean)=>void;onNearbyStation:(n:number|null)=>void;onError:()=>void};
const stationPositions=[[-7,3],[-2,-3],[4,-3],[8,4]];
export default function PukuScene(props:SceneProps){const mount=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;
useEffect(()=>{if(!mount.current)return;const host=mount.current;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{latest.current.onError();return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;host.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color('#B9BCD4');scene.fog=new T.FogExp2('#B9BCD4',.004);const camera=new T.PerspectiveCamera(42,1,.1,240);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=5;controls.maxDistance=145;controls.maxPolarAngle=Math.PI*.485;controls.target.set(-22,1.5,0);camera.position.set(-3,20,27);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.025);scene.environment=env.texture;scene.environmentIntensity=.55;
 const hemi=new T.HemisphereLight('#F5F1FF','#73718F',2.3);scene.add(hemi);const sun=new T.DirectionalLight('#FFF1DB',4);sun.position.set(-30,60,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:.1,far:180});sun.shadow.bias=-.0003;scene.add(sun);
 const mat={floor:new T.MeshStandardMaterial({color:'#B6B7C4',roughness:.82}),wall:new T.MeshStandardMaterial({color:'#DEE0E8',roughness:.7}),steel:new T.MeshStandardMaterial({color:'#393E59',roughness:.42,metalness:.65}),navy:new T.MeshStandardMaterial({color:BRAND.navy,roughness:.45,metalness:.35}),purple:new T.MeshStandardMaterial({color:BRAND.violet,roughness:.45,metalness:.3}),blue:new T.MeshStandardMaterial({color:BRAND.blue,roughness:.5}),glass:new T.MeshPhysicalMaterial({color:'#C7C2FF',roughness:.1,transparent:true,opacity:.2,side:T.DoubleSide}),wood:new T.MeshStandardMaterial({color:'#A48D79',roughness:.78}),green:new T.MeshStandardMaterial({color:'#738579',roughness:.9})};
 const glow=(color:string)=>new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.7,roughness:.35});const purpleGlow=glow(BRAND.violet),whiteGlow=glow('#F0E9FF'),successGlow=glow(BRAND.success),failureGlow=glow(BRAND.failed),warningGlow=glow(BRAND.warning);const hits:T.Object3D[]=[];
 function box(w:number,h:number,d:number,x:number,y:number,z:number,material:T.Material,parent:T.Object3D=scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function cylinder(r:number,h:number,x:number,y:number,z:number,material:T.Material,parent:T.Object3D=scene){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,48),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function ring(radius:number,y:number,material:T.Material,parent:T.Object3D){const m=new T.Mesh(new T.TorusGeometry(radius,.035,8,64),material);m.rotation.x=-Math.PI/2;m.position.y=y;parent.add(m);return m;}
 function label(text:string,x:number,y:number,z:number,width:number,parent:T.Object3D=scene,color='#ECE7FF'){const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=BRAND.navy;ctx.fillRect(0,0,1024,128);ctx.fillStyle=color;ctx.font='500 43px Arial';ctx.textAlign='center';ctx.fillText(text,512,81);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const mesh=new T.Mesh(new T.PlaneGeometry(width,width/8),new T.MeshBasicMaterial({map:texture,side:T.DoubleSide}));mesh.position.set(x,y,z);parent.add(mesh);mesh.visible=true;return mesh;}
 box(210,.6,210,0,-1.2,0,new T.MeshStandardMaterial({color:'#9EA2B9',roughness:1}));box(84,.5,77,0,-.5,-18,mat.floor);for(let i=-40;i<=40;i+=4){box(.018,.013,75,i,-.24,-18,mat.steel);box(83,.013,.018,0,-.24,i-18,mat.steel);}box(9,.05,75,0,-.2,-18,mat.navy);box(82,.05,7,0,-.19,-17.5,mat.navy);
 const districtLights:T.Mesh[]=[];const halls:T.Group[]=[];
 milestones.forEach((m,index)=>{const g=new T.Group();g.position.set(m.position[0],0,m.position[1]);scene.add(g);halls.push(g);box(29,.4,27,0,0,0,mat.navy,g);box(28.5,.16,26.5,0,.28,0,mat.floor,g);box(29,6,.4,0,3.5,-13.5,mat.wall,g);box(.4,6,27,-14.5,3.5,0,mat.wall,g);box(.12,5.8,27,14.5,3.4,0,mat.glass,g);for(let x=-14;x<=14;x+=7){box(.2,6.6,.2,x,3.5,13.1,mat.steel,g);box(.2,.3,27,x,6.8,0,mat.steel,g);}box(29,.4,.5,0,6.7,13.2,mat.navy,g);box(29,.5,5,0,6.7,-11,mat.navy,g);box(28,.06,.1,0,6.35,-8.5,whiteGlow,g);const strip=box(28,.09,.1,0,.4,13,mat.blue,g);districtLights.push(strip);label(`0${index+1}   /   ${m.district.toUpperCase()}`,0,5.4,-13.25,25,g);label(`MILESTONE ${index+1}`,0,5.7,13.48,10,g);
 for(let k=0;k<3;k++){box(3,1.2,1.7,-8+k*8,1,-9.5,mat.navy,g);box(2.5,.9,.1,-8+k*8,2,-10,mat.blue,g);}for(let k=0;k<2;k++){cylinder(.65,.7,-12,.75,8-k*4,mat.wood,g);const plant=new T.Mesh(new T.SphereGeometry(.9,12,8),mat.green);plant.position.set(-12,1.8,8-k*4);plant.scale.y=1.4;plant.castShadow=true;g.add(plant);}
 });
 for(let z=-46;z<14;z+=8){box(.1,2,.1,-4,1,z,mat.steel);box(.7,.07,.7,-4,2,z,whiteGlow);box(.1,2,.1,4,1,z,mat.steel);box(.7,.07,.7,4,2,z,whiteGlow);}
 label('P O R I D H I  /  P U K U  L E A R N I N G  W O R L D',0,3.6,25,25);box(30,.3,3,0,.2,23,mat.navy);
 const active=new T.Group();scene.add(active);let stationLabels:T.Mesh[]=[];const stationRings:T.Mesh[]=[];
 stationPositions.forEach(([x,z],i)=>{const g=new T.Group();g.position.set(x,0,z);active.add(g);box(3.2,.28,2.8,0,.6,0,mat.steel,g);box(2.4,1.1,1.5,0,1.25,0,mat.navy,g);const screen=box(2.05,.92,.07,0,2,-.3,mat.blue,g);screen.rotation.x=-.18;screen.userData.station=i;hits.push(screen);const top=box(2.4,.1,1.6,0,1.84,0,mat.purple,g);top.userData.station=i;hits.push(top);box(.65,.04,.4,0,1.91,.35,whiteGlow,g);const light=ring(1.7,.45,purpleGlow,g);stationRings.push(light);const text=label(`${i+1} / STATION`,0,2.9,-.15,4.3,g);text.userData.station=i;hits.push(text);stationLabels.push(text);});
 // The learning installation changes state rather than using a decorative screen.
 const installation=new T.Group();installation.position.set(0,0,-7);active.add(installation);cylinder(3.8,.35,0,.55,0,mat.navy,installation);ring(3.6,.8,purpleGlow,installation);const chamber=box(5,4.6,3.4,0,3,0,mat.glass,installation);const frame=box(5.25,.22,3.6,0,5.35,0,mat.steel,installation);box(.14,4.6,.14,-2.55,3,1.75,mat.steel,installation);box(.14,4.6,.14,2.55,3,1.75,mat.steel,installation);const fillBlocks:T.Mesh[]=[];for(let i=0;i<16;i++){const c=box(.95,.7,.85,(i%2-.5)*1.5,1.4+Math.floor(i/2)*.9,0,mat.purple,installation);fillBlocks.push(c);}
 const gear=new T.Group();gear.position.set(0,3,-7);active.add(gear);const jewel=new T.Mesh(new T.OctahedronGeometry(1.2,0),new T.MeshStandardMaterial({color:BRAND.violet,metalness:.65,roughness:.25}));gear.add(jewel);const wire=new T.LineSegments(new T.EdgesGeometry(jewel.geometry),new T.LineBasicMaterial({color:'#E7D5FF'}));jewel.add(wire);const orbit=ring(1.8,0,whiteGlow,gear);orbit.rotation.x=.35;
 const gate=box(4.5,3.8,.3,0,2.8,-4.5,mat.purple,active);const gatePostL=box(.25,4.7,.5,-2.5,2.9,-4.5,mat.steel,active),gatePostR=box(.25,4.7,.5,2.5,2.9,-4.5,mat.steel,active);
 const nodeGroup=new T.Group();nodeGroup.position.set(0,0,-7);active.add(nodeGroup);const nodes:T.Group[]=[];for(let i=0;i<8;i++){const g=new T.Group();g.position.set((i%4-1.5)*2.15,0,Math.floor(i/4)*2.3);nodeGroup.add(g);box(1.5,2.7,1.6,0,1.75,0,mat.navy,g);for(let j=0;j<6;j++){box(1.3,.18,.06,0,.7+j*.35,.83,mat.steel,g);box(.07,.06,.08,.48,.72+j*.35,.87,successGlow,g);}box(.8,.35,.65,0,3.4,0,purpleGlow,g);nodes.push(g);}
 const productionLine=new T.Group();productionLine.position.set(0,0,-7);active.add(productionLine);const productionCrates:T.Mesh[]=[];const productionLamps:T.Mesh[]=[];box(12,.35,2.2,0,.65,0,mat.steel,productionLine);for(let i=0;i<5;i++){const x=-4.8+i*2.4;box(.08,1.5,1.8,x,1.4,0,mat.navy,productionLine);const crate=box(1.3,1.1,1.2,x,1.4,0,mat.blue,productionLine);productionCrates.push(crate);const lamp=box(1.5,.08,.1,x,2.3,.7,mat.blue,productionLine);productionLamps.push(lamp);label(['SOURCE','BUILD','TEST','SECURITY','DEPLOY'][i],x,2.7,.7,2,productionLine);}
const projectFile=new T.Group();projectFile.position.set(0,0,-7);active.add(projectFile);box(5,.25,3.5,0,.75,0,mat.navy,projectFile);const files:T.Mesh[]=[];for(let i=0;i<3;i++){const f=box(2.8,.11,2,0,1.15+i*.4,0,mat.wall,projectFile);files.push(f);}label('PROJECT FILESYSTEM',0,3.1,1.05,6,projectFile);const projectCheck=box(2.8,.08,.1,0,1.05,1.1,mat.blue,projectFile);
const archive=new T.Group();archive.position.set(6,0,-8);active.add(archive);box(2.4,3.8,1.6,0,2.3,0,mat.navy,archive);const archiveDoor=box(2.1,3.5,.15,0,2.3,.85,mat.blue,archive);label('MEMORY',0,4.5,.9,3,archive);const archiveData=box(.7,.7,.7,0,2.3,1,successGlow,archive);
 const agents=[0,1,2].map((i)=>{const a=createPuku(.7,['#484FA3','#8940F8','#7778AD'][i]);a.root.position.set(-6+i*6, .4,-5);active.add(a.root);return a;});
 const dataPaths:T.Mesh[]=[];for(let i=0;i<4;i++){const m=box(.045,.03,6,-6+i*4,.43,-2,mat.purple,active);dataPaths.push(m);}const puck=new T.Mesh(new T.SphereGeometry(.2,16,12),whiteGlow);puck.position.y=1;active.add(puck);
 const puku=createPuku();scene.add(puku.root);puku.root.position.set(-22,.4,8);const carry=box(.55,.55,.15,.3,1.15,.65,mat.purple,puku.root);carry.visible=false;
 const selection=new T.Group();scene.add(selection);const marker=ring(.7,.43,purpleGlow,selection);let currentModule='',currentSelected=-1,lastNonce=-1,lastView='',lastQuality='',destination:T.Vector3|null=null,queued:string|null=null,near=true,camMove=1,elapsed=0,interactionUntil=0,lastSerial=-1,nearStation:number|null=null,frameId=0,lastTime=performance.now();const cameraGoal=new T.Vector3(),targetGoal=new T.Vector3();const keys=new Set<string>();
 const choose=(i:number)=>latest.current.onStation(i);let down=[0,0];const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=renderer.domElement.getBoundingClientRect();const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const h=ray.intersectObjects(hits).find(h=>h.object.visible);if(h)choose(h.object.userData.station);};
 const keyDown=(e:KeyboardEvent)=>{if(/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement)?.tagName)||document.querySelector('[role="dialog"]'))return;if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Shift'].includes(e.key)){e.preventDefault();keys.add(e.key);}};const keyUp=(e:KeyboardEvent)=>keys.delete(e.key);const blur=()=>keys.clear();window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);controls.addEventListener('start',()=>camMove=0);
 const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(host);resize();
 function replaceStationLabels(names:string[]){stationLabels.forEach((m,i)=>{const parent=m.parent!;parent.remove(m);m.geometry.dispose();const material=m.material as T.MeshBasicMaterial;material.map?.dispose();material.dispose();hits.splice(hits.indexOf(m),1);const n=label(`${i+1} / ${names[i]||'VERIFY'}`,0,2.9,-.15,4.3,parent);n.userData.station=i;hits.push(n);stationLabels[i]=n;});}
 function animate(time:number){frameId=requestAnimationFrame(animate);const dt=Math.min((time-lastTime)/1000,.05);lastTime=time;const p=latest.current,s=p.state,m=modules.find(m=>m.id===s.moduleId)!;const district=milestones[m.milestone-1];const dx=district.position[0],dz=district.position[1];if(!p.paused)elapsed+=dt*p.speed;
 if(currentModule!==m.id){currentModule=m.id;active.position.set(dx,0,dz);puku.root.position.set(dx,.4,dz+8);destination=null;queued=null;currentSelected=-1;lastView='';near=true;p.onNear(true);replaceStationLabels(m.objects.slice(0,4).map(o=>o.toUpperCase()));}
 if(currentSelected!==p.selected){currentSelected=p.selected;const [x,z]=stationPositions[p.selected];destination=new T.Vector3(dx+x,.4,dz+z+2.2);queued=null;camMove=1;selection.position.set(dx+x,0,dz+z+2.2);}
 if(!p.command&&queued){queued=null;destination=null;}
 if(p.command&&p.command.nonce!==lastNonce){lastNonce=p.command.nonce;const [x,z]=stationPositions[p.command.action.station];destination=new T.Vector3(dx+x,.4,dz+z+2.2);queued=p.command.action.id;interactionUntil=0;}
 if(lastView!==p.view){lastView=p.view;camMove=1;}
 if(lastQuality!==p.quality){lastQuality=p.quality;renderer.setPixelRatio(Math.min(devicePixelRatio,p.quality==='high'?2:p.quality==='medium'?1.5:1));renderer.shadowMap.enabled=p.quality!=='low';resize();}
 let moving=false,running=keys.has('Shift');if(!p.paused){const inputX=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0);const inputZ=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);if((inputX||inputZ)&&!queued){destination=null;queued=null;const direction=new T.Vector3(inputX,0,inputZ).normalize();puku.root.position.addScaledVector(direction,dt*(running?7:4)*p.speed);puku.root.position.x=T.MathUtils.clamp(puku.root.position.x,dx-12,dx+12);puku.root.position.z=T.MathUtils.clamp(puku.root.position.z,dz-10,dz+12);puku.root.rotation.y=Math.atan2(direction.x,direction.z);moving=true;}else if(destination){const direction=destination.clone().sub(puku.root.position);const dist=direction.length();if(dist>.07&&!p.reduced){direction.normalize();puku.root.position.addScaledVector(direction,Math.min(dist,dt*5*p.speed));puku.root.rotation.y=Math.atan2(direction.x,direction.z);moving=true;}else{puku.root.position.copy(destination);destination=null;puku.root.rotation.y=Math.PI;if(queued){interactionUntil=elapsed+(p.reduced?0:.55);}}}
 if(queued&&!destination&&elapsed>=interactionUntil){const action=queued;queued=null;p.onArrive(action);interactionUntil=elapsed+.8;}
 }
 let nextStation:number|null=null,stationDistance=3.5;stationPositions.forEach(([x,z],i)=>{const distance=puku.root.position.distanceTo(new T.Vector3(dx+x,.4,dz+z+2.2));if(distance<stationDistance){stationDistance=distance;nextStation=i;}});if(nextStation!==nearStation){nearStation=nextStation;p.onNearbyStation(nextStation);}
 const [sx,sz]=stationPositions[p.selected];const nowNear=puku.root.position.distanceTo(new T.Vector3(dx+sx,.4,dz+sz+2.2))<3.5;if(nowNear!==near){near=nowNear;p.onNear(near);}const react=queued||elapsed<interactionUntil?'working':s.reaction;puku.animate(elapsed,moving,running,react,p.reduced||p.paused);carry.visible=moving&&Boolean(queued)&&['context','memory','container','retrieval'].includes(m.kind);
 const contextMode=['context','memory','retrieval'].includes(m.kind);const gateMode=['permissions','rules','guardrails','mcp'].includes(m.kind);const nodeMode=['cluster','design','production'].includes(m.kind);const agentsMode=['delegation','orchestration'].includes(m.kind);const lineMode=['container','pipeline','capstone'].includes(m.kind);const fileMode=['workflow','project','loop','tools'].includes(m.kind);chamber.visible=frame.visible=contextMode;fillBlocks.forEach((b,i)=>{b.visible=contextMode&&i<Math.ceil(s.context/10);b.scale.y=Math.max(.05,Math.min(1,(s.context-i*10)/10));b.material=s.context>100?failureGlow:mat.purple;});gear.visible=false;productionLine.visible=lineMode;projectFile.visible=fileMode;files.forEach((file,i)=>{file.visible=i<Math.max(1,s.step);file.material=s.step>=3?mat.purple:mat.wall;});projectCheck.material=s.status==='success'?successGlow:s.status==='failed'?failureGlow:mat.blue;productionCrates.forEach((crate,i)=>{crate.visible=i<Math.max(1,s.flags.length+(s.status==='success'?5:0));crate.material=s.status==='success'?mat.purple:mat.blue;productionLamps[i].material=s.status==='success'?successGlow:s.status==='failed'&&i===s.step?failureGlow:i<s.flags.length?purpleGlow:mat.blue;});gate.visible=gatePostL.visible=gatePostR.visible=gateMode;gate.position.y=(s.status==='success'||s.flags.includes('approved')||s.step>=3)?6.5:2.8;gate.material=s.status==='failed'?failureGlow:s.status==='success'?successGlow:mat.purple;nodes.forEach((n,i)=>{n.visible=nodeMode&&i<s.nodes;n.traverse(o=>{if(o instanceof T.Mesh&&o.geometry.type==='BoxGeometry'&&o.geometry.parameters.width===.07)o.material=i<s.failedNodes?failureGlow:successGlow;});n.position.y=i<s.failedNodes?-.1:0;});archive.visible=contextMode;archiveData.visible=s.archived;archiveDoor.material=s.archived?mat.purple:mat.blue;agents.forEach((a,i)=>{a.root.visible=agentsMode;a.animate(elapsed+i,false,false,s.flags.includes('results')||s.status==='success'?'success':s.flags.length>i?'working':'idle',p.reduced||p.paused);});
 if(!p.paused&&!p.reduced){jewel.rotation.y=elapsed*.2;orbit.rotation.z=elapsed*.15;}jewel.material=s.status==='success'?successGlow:s.status==='failed'?failureGlow:mat.purple;jewel.scale.setScalar(.8+machineFill(s)/180);dataPaths.forEach((path,i)=>path.material=s.status==='success'?successGlow:i<Math.max(s.step,s.flags.length)?purpleGlow:mat.blue);puck.visible=!p.paused&&s.status==='active'&&!p.reduced;puck.position.set(Math.sin(elapsed)*4,1,-3+Math.cos(elapsed)*3);stationRings.forEach((r,i)=>{r.material=i===p.selected?whiteGlow:purpleGlow;r.visible=i===p.selected;});districtLights.forEach((light,i)=>{const list=modules.filter(m=>m.milestone===i+1);light.material=list.every(m=>s.completed.includes(m.id))?successGlow:mat.blue;});marker.visible=near;
 if(p.view==='map'){cameraGoal.set(56,75,65);targetGoal.set(0,0,-18);}else if(p.view==='close'){cameraGoal.set(dx+sx+5,5.5,dz+sz+9);targetGoal.set(dx+sx,1.8,dz+sz);}else{cameraGoal.set(puku.root.position.x+14,13,puku.root.position.z+18);targetGoal.set(dx+(puku.root.position.x-dx)*.35,1.8,dz-2);if(moving)camMove=1;}
 if(camMove&&!p.paused){const alpha=p.reduced?1:1-Math.exp(-dt*3.5);camera.position.lerp(cameraGoal,alpha);controls.target.lerp(targetGoal,alpha);if(camera.position.distanceTo(cameraGoal)<.08)camMove=0;}
 if(lastSerial!==s.serial){lastSerial=s.serial;}
 controls.update();renderer.render(scene,camera);
 }
 frameId=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(frameId);ro.disconnect();controls.dispose();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);const geometrySet=new Set<T.BufferGeometry>(),materialSet=new Set<T.Material>(),textureSet=new Set<T.Texture>();scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.LineSegments){geometrySet.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materialSet.add(m));}});materialSet.forEach(m=>{const map=(m as T.MeshStandardMaterial).map;if(map)textureSet.add(map);m.dispose();});geometrySet.forEach(g=>g.dispose());textureSet.forEach(t=>t.dispose());env.dispose();pmrem.dispose();room.dispose();renderer.dispose();renderer.domElement.remove();};
},[]);
return <div className="puku-scene" ref={mount} role="img" aria-label="Puku in the connected Poridhi learning world. Equivalent controls and live state are available alongside the 3D view."/>;
}
